// Shared esbuild options for the Appwrite function bundle.
//
// Consumers:
//  - scripts/functions/build.mjs            (npm run functions:build)
//  - scripts/functions/build-function.mjs   (the function's package.json build)
//
// Appwrite's Git deploy does NOT bundle — it activates the committed
// dist/main.js this produces. Stays a plain default export, spread into the
// esbuild API call.

export default {
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node22',
  // Installed by the Appwrite runtime from each function's package.json —
  // never bundled (firebase-admin carries optional native/cloud deps; pino
  // spawns a worker thread by path, which breaks inside a single-file bundle;
  // puppeteer has no Chromium in the Appwrite runtime and its dynamic import
  // already fails gracefully in rss/fetch.ts).
  external: [
    'firebase-admin',
    'node-appwrite',
    'puppeteer',
    'puppeteer-core',
    // got-scraping breaks when inlined: its ESM/CJS interop mangled
    // ("gotScraping is not a function") and its header-generator reads
    // data_files/headers-order.json from its own package folder, which is
    // lost in a single-file bundle. tough-cookie is another dual package used
    // via dynamic import.
    'got-scraping',
    'tough-cookie',
    // jsdom reads lib/jsdom/browser/default-stylesheet.css via require.resolve
    // at document creation — that file is lost in a single-file bundle
    // (ENOENT) and the inlined interop breaks "new JSDOM(...)". Keep it
    // external so the real package is installed by the function's npm install.
    'jsdom',
    '@mozilla/readability',
    'pino',
    'pino-pretty',
    'thread-stream',
    'sonic-boom',
  ],
  logLevel: 'warning',
  banner: { js: '/* Generated by apps/backend functions build — do not edit. */' },
};