// Shared esbuild options for every Appwrite function bundle.
//
// Consumers:
//  - scripts/functions/build.mjs           (local/manual builds, esbuild JS API)
//  - scripts/functions/build-function.mjs   (each function's package.json
//    "build" script, run by Appwrite's Git-connected build step)
//
// Stays a plain default export — spread into the esbuild API call.

export default {
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  // Installed by the Appwrite runtime from each function's package.json —
  // never bundled (firebase-admin carries optional native/cloud deps; pino
  // spawns a worker thread by path, which breaks inside a single-file bundle;
  // puppeteer has no Chromium in the Appwrite runtime and its dynamic import
  // already fails gracefully in rss/fetch.ts).
  external: [
    'firebase-admin',
    'node-appwrite',
    'puppeteer',
    'puppeteer-core',
    'pino',
    'pino-pretty',
    'thread-stream',
    'sonic-boom',
  ],
  logLevel: 'warning',
  banner: { js: '/* Generated by apps/backend functions build — do not edit. */' },
};